print("Hello world")
naam = input("Wie ben jij\n")
print("Yo " + naam)
print("je naam is "+ str(len(naam)) +" tekens lang")
woonstraat = input("welke straat woon je\n")
huisnr = input("Wat is je huis nummer\n")
print("Je woont op " + woonstraat +" "+ huisnr)